### ISSUE TITLE
[BucketIterator] Error: User 'root' is not allowed to read records on type ...

### ISSUE THREAD

**Issue by shasaur** [ArcadeData/arcadedb#1251]
### ArcadeDB Version:
ArcadeDB Server v23.2.1 is my main version. I also tried the latest ArcadeDB build but no success.

### OS and JDK Version:
Windows 11

Hey guys, I am absolutely wrecking myself here debugging the DB 😭

I'm getting into a situation where some of my queries seem to get the DB stuck, such that although future queries return correctly, new information is not persisted

Like:
Query A -> Result A -> Persist A
Query B -> Result B -> Persist B
Break
Query C -> Result C -> Persist B
Query D -> Result D -> Persist B

I've just been investigating through the console, and I saw a couple of things:

```
...
|warnings               |1[edge #261:499 points to the outgoing vertex #245:498 that is not found (deleted?)]|
...
|corruptedRecords       |2[#261:499,#245:498]
...
```

I run the `check database fix` command and it fixed the corruptions. That seemed to help somewhat at first, however, after continuing to run my server with its queries, I got back into the same problem outlined above and got a probably related error: `2023-09-24 04:16:33.777 SEVER [BucketIterator] Error on loading record #451:4451 (error: User 'root' is not allowed to read records on type 'Building')"`

Note: other queries are running fine, it's just the queries relating to these data blocks that seem to mess up. Even once the break happens, the other non-related queries continue to run fine. Restarting fixes things until they break again.

Any help or guidance?

**Comment by shasaur** [comment]
I should note, running the `check database` script found no further corruptions despite the continued errors.

**Comment by shasaur** [comment]
I should further add, sometimes this situation happens and I see no error from the ArcadeDB server at all, so it could be that the last error I posted is actually an unrelated issue.

**Comment by lvca** [comment]
We fixed that issues months ago. Is there a particular reason why you're using the release from February?

**Comment by shasaur** [comment]
Hey Luca, thanks for the quick response.

I was testing with the latest version of ArcadeDB but I still experienced the initial issue I mention. However, you are right that I don't get that error in the console. It's more like a silent fail with the latest version.

Any other info I can provide you with or direction you can point me in?

**Comment by lvca** [comment]
I'd need to see what your code looks like when you execute the transaction that persists the records. Without a test case, it's hard to guess. We've seen some issues with reusing immutable vertex instances on multiple transactions when the `newEdge()` is called on the cached version that isn't the latest. We're checking how to enforce the API for such issues, but I'm not sure this is the same case.  Any chance you can share that piece of code?

**Comment by shasaur** [comment]
At the moment, the queries that are causing the issues are in a nestled web of transactions called from all over the place at run-time, it's hard for me identify which specific one is causing the issue. However, I'll see if I can try to isolate it more today, maybe I can build up a test case.

**Comment by shasaur** [comment]
Might it be useful if I provide the txlog_x.wal files? I feel like if there are some transactions that become stuck or something, those could reveal them.

**Comment by lvca** [comment]
In the last 2y, the transaction log (WAL) logic was never the issue, it was always something around that. I think it's more likely to be in how the tx is used.

This is an example of what we found can create an issue with the consistency of the graph:

```java
Vertex account = // get the vertex from a query/lookup
database.transaction( ()-> {
  account.modify().set("something", "anything").save();
});
account.newEdge("myEdge", anotherVertex, true);
```

This can cause problems on the first edge because the `vertex` object outside the transaction wouldn't be update with the most recent vertex from the transaction.

Do you have a case like this?

**Comment by shasaur** [comment]
All my queries are ran through a simple cypher wrapper transaction function:

```
func (s *ArcadeSession) WriteTransaction(
	work neo4j.TransactionWork, configurers ...func(*neo4j.TransactionConfig)) (interface{}, error) {

	transaction := &transaction{
		run: func(cypher string, params map[string]interface{}) (neo4j.Result, error) {
			cypher = patchQueryWithParams(cypher, params)
			cypher = fmt.Sprintf("{cypher} %s;", cypher)

			sqlResults, err := s.db.Query(cypher)
			if err != nil {
				return nil, err
			}

			newResult := &result{}
			newResult.sqlResults = sqlResults

			return newResult, err
		},
		session: s,
	}

	results, err := work(transaction)

	if err != nil {
		s.db.Exec("ROLLBACK")
		return nil, err
	}

	// Save results
	transaction.Commit()

	return results, err
}
```

**Comment by shasaur** [comment]
Hmm, perhaps I found the issue (or at least an issue). Does ArcadeDB support multiple concurrent sessions?

This code results in the incorrect number of buildings and items being added:
```
var counter int
var wg sync.WaitGroup // Using a WaitGroup to wait for all goroutines to finish

func main() {
	SpawnInRaceCondition()
	SpawnInRaceCondition()
	SpawnInRaceCondition()
	SpawnInRaceCondition()

	wg.Wait()
}

func SpawnInRaceCondition() {
	wg.Add(2)
	go func() {
		session, _ := db_preconfigured.ConnectToDatabase(true)
		AddNewBuilding(session)
		wg.Done()
	}()

	go func() {
		session, _ := db_preconfigured.ConnectToDatabase(true)
		AddItemsAndPrint(session)
		wg.Done()
	}()
}
```

Added a mutex lock to forces transactions to be sequential and results in the correct number of buildings and items added:
```
var counter int
var wg sync.WaitGroup // Using a WaitGroup to wait for all goroutines to finish
var mutex sync.Mutex  // Mutex lock to prevent race conditions

func main() {
	SpawnInRaceCondition()
	SpawnInRaceCondition()
	SpawnInRaceCondition()
	SpawnInRaceCondition()

	wg.Wait()
}

func SpawnInRaceCondition() {
	wg.Add(2)
	go func() {
		mutex.Lock() // Locking

		session, _ := db_preconfigured.ConnectToDatabase(true)
		AddNewBuilding(session)

		mutex.Unlock()

		wg.Done()
	}()

	go func() {
		mutex.Lock() // Locking

		session, _ := db_preconfigured.ConnectToDatabase(true)
		AddItemsAndPrint(session)

		mutex.Unlock()

		wg.Done()
	}()
}
```

**Comment by lvca** [comment]
Are you using ArcadeDB embedded? (a language on top of the JVM), via HTTP/JSON or Postgres driver?

Concurrency is supported, all the transactions are in parallel, but since we use an optimistic tx approach, if 2 transactions modify the same page, the 2nd transaction is aborted with a `ConcurrentModificationException`. The client usually retries the transaction. In Java, this is built into the API, so it's quite transparent.

How do you catch the `ConcurrentModificationException` in your code?

**Comment by shasaur** [comment]
Nope, I did not know about the embedded feature. That's pretty cool but I'm using golang for the server app.

In regards to the exceptions, I assume it would be caught and rolled back (excerpt from wrapper code above):

```
if err != nil {
	s.db.Exec("ROLLBACK")
	return nil, err
}
```

In either case, I've introduced a mutex lock for all the transactions in my app as a safe fix for now, and it seems to have solved the issues. I may investigate the concurrency at some point.

**Comment by lvca** [comment]
Check out how ArcadeDB manages transactions: https://docs.arcadedb.com/#_optimistic-transaction, when you are ready, because if you don't have a lot of conflicts with pages, you can scale up a lot by using multi-core/cpu.

**Comment by lvca** [comment]
This issue has been already fixed in a previous release. If you see this happening again, please comment on this issue.
