### ISSUE TITLE
HTTP-API: "limit" request property ignored for non-SQL

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#1661]
### ArcadeDB Version:

`ArcadeDB Server v24.6.1-SNAPSHOT (build d21f2f50234cec7f64bf4ab1a1118b2e76c5f0a8/1721165296536/main)`

### OS and JDK Version:

`Running on Mac OS X 12.7.5 - OpenJDK 64-Bit Server VM 17.0.12 (Homebrew)`

### Expected behavior

The `limit` property in a query or command request returns the limited amount of items.

### Actual behavior

The `limit` property seems to work only for `SQL`. For `Cypher` and `Gremlin` it fails and returns all query results. I assume it also fails for `MQL` and `GraphQL`.

### Steps to reproduce

Prepare dataset in a database `test`:
```sql
CREATE VERTEX TYPE vec;
INSERT INTO vec;
INSERT INTO vec;
INSERT INTO vec;
INSERT INTO vec;
INSERT INTO vec;
```

SQL limit works:
```shell
wget -qO- http://localhost:2480/api/v1/query/test --post-data='{"language":"sql","command":"SELECT FROM vec","limit":3}' --user=root --password=arcadedb
```

Cypher limit fails, returns all vertices:
```shell
wget -qO- http://localhost:2480/api/v1/query/test --post-data='{"language":"cypher","command":"MATCH (m:vec) RETURN m","limit":3}' --user=root --password=arcadedb
```
Gremlin limit fails, returns all vertices:
```shell
wget -qO- http://localhost:2480/api/v1/query/test --post-data='{"language":"gremlin","command":"g.V().hasLabel(\"vec\")","limit":3}' --user=root --password=arcadedb
```

**Comment by gramian** [comment]
Here is the problem: https://github.com/ArcadeData/arcadedb/blob/main/server/src/main/java/com/arcadedb/server/http/handler/PostCommandHandler.java#L78

**Comment by lvca** [comment]
The limit in the get /query is used to cut the result, not in the query itself. So it should work with any language because it acts when it serializes the resultset. Checking the code, I see the limit is not used only in the `graph` serializer that I assume is the one you're using. Fixing it right now.

**Comment by gramian** [comment]
Your fix seems to work, but is off by one, meaning one element is missing, so a limit of 2 returns only 1 vertex.

Thanks for the quick fix

**Comment by lvca** [comment]
Not sure to understand if it's fixed or not, but I've pushed another fix that consider the limit also for vertices and edges across all the serializers

**Comment by gramian** [comment]
Sorry, no it still does not fix it. The problem remains:

* it only works if the language is `sql` and `sqlscript` and the limit is greater or equal to four.
* For languages `cypher`, `gremlin`, with limit greater or equal than four all vertices are returned.
* For all languages with limit 1, 2, 3 only one vertex is returned.

**Comment by gramian** [comment]
Fixed by https://github.com/ArcadeData/arcadedb/commit/df5e8d727c4820e7e8a2f52e681830d4137a7610 .
