### ISSUE TITLE
SQL `default` constraint for `STRING` and `DATETIME` 

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#905]
### OS: MacOS 12.6

The default values for strings and datetime seem not to work when set in `CREATE PROPERTY`. When set after creation by `ALTER PROPERTY`, it works. Checking the return values from `CREATE PROPERTY` it seems the default values are still `null` after `CREATE PROPERTY`. However, a default value for `LONG` works already with `CREATE PROPERTY`. Also, using double quotes `"` instead of single quotes `'` does also not work.

## Steps to reproduce
```
CREATE DOCUMENT TYPE doc;
CREATE PROPERTY doc.num LONG (default 1);
CREATE PROPERTY doc.str STRING (default 'Hi');
CREATE PROPERTY doc.dat DATETIME (default sysdate('YYYY-MM-DD HH:MM:SS'));
```
This makes it work as expected:
```
ALTER PROPERTY doc.str default 'Hi';
ALTER PROPERTY doc.dat default sysdate('YYYY-MM-DD HH:MM:SS');

**Comment by lvca** [comment]
Fixed, thanks!

**Comment by gramian** [comment]
@lvca this seems to be still not fixed, defining:
```
CREATE DOCUMENT TYPE doc;
CREATE PROPERTY doc.str STRING (mandatory true, notnull true, default 'Hi');
CREATE PROPERTY doc.dat DATETIME (mandatory true, default null);
``` 
and inserting:
```
INSERT INTO doc;
INSERT INTO doc SET str = 'X';
INSERT INTO doc SET dat = null;
```
each fail in studio or console.

---

The simpler case of:
```
CREATE DOCUMENT TYPE doc;
CREATE PROPERTY doc.str STRING (default 'Hi');
CREATE PROPERTY doc.dat DATETIME (default null);
```
produces on `INSERT INTO doc` a record with `doc.str = null` and no `doc.dat`.

**Comment by lvca** [comment]
Reproduced

**Comment by gramian** [comment]
Works! Thank you for fixing this.

**Comment by TimMensch** [comment]
Is this really fixed?

When I say:

```
CREATE VERTEX TYPE Test;
CREATE PROPERTY Test.createdAt IF NOT EXISTS DATETIME (mandatory true, readonly, DEFAULT sysdate());
CREATE VERTEX Test; -- Wait a couple of seconds
CREATE VERTEX Test; -- Wait a couple of seconds 
CREATE VERTEX Test;
```

The three vertices all have the same createdAt field. Whereas if I say:

```
ALTER PROPERTY Test.createdAt DEFAULT sysdate();
```

Then 

```
CREATE VERTEX Test;  -- Wait a couple of seconds
CREATE VERTEX Test;  -- Wait a couple of seconds
CREATE VERTEX Test;
```

...creates vertices with three unique timestamps.

So it seems like this bug still occurs. I'm using the Docker Hub image version 24.4.1.
